### ISSUE TITLE
more detailed documentation

### ISSUE THREAD

**Issue by ghost** [dance2die/cra-template-tailwindcss-typescript#17]
Hi,

I manage to add your template with the npx command. But I have some questions

(1) you say we enable JIT by changing tailwind.config.js to add "mode: "jit"," but what about postcss.config.js that still looks the following? Shouldn't that be changed as well "tailwindcss" to "tailwindcss/hit" ? 

```
module.exports = {
  plugins: [
    require('tailwindcss'),
    require('postcss-preset-env'),
  ],
};
```

(2) IMPORTANT: Do NOT comment purge when you enable JIT mode, otherwise your CSS will be empty!
- But can we comment out at all? Can I comment out purge after JIT mode is enabled? 

(3) As this is a custom build tailwind project how do we use it? 
When to run the following scripts:

build:css": "cross-env TAILWIND_MODE=build NODE_ENV=production postcss src/styles/tailwind.css -o src/styles/index.css",
 "watch:css": "cross-env TAILWIND_MODE=watch NODE_ENV=development postcss src/styles/tailwind.css -o src/styles/index.css --watch",
"react-scripts:start": "sleep 5 && react-scripts start",

**Comment by dance2die** [comment]
Thank you for checking out the template.

Good questions @stephyswe~

> (1) you say we enable JIT by changing tailwind.config.js to add "mode: "jit"," but what about postcss.config.js that still looks the following? Shouldn't that be changed as well "tailwindcss" to "tailwindcss/hit" ?

`postcss.config.js` can stay the same. 
Can you refer me to `tailwindcss/hit` because I can't find anything on it :sweat: 

> (2) IMPORTANT: Do NOT comment purge when you enable JIT mode, otherwise your CSS will be empty!
> But can we comment out at all? Can I comment out purge after JIT mode is enabled?

You can NOT comment out the purge section because your CSS will be empty otherwise.
https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode

![jit](https://user-images.githubusercontent.com/8465237/119233300-5ffbf100-baf6-11eb-9027-a4ab401bd71e.png)

> (3) As this is a custom build tailwind project how do we use it?
> When to run the following scripts:

```json
{
  "scripts":{
    "build:css":"cross-env TAILWIND_MODE=build NODE_ENV=production postcss src/styles/tailwind.css -o src/styles/index.css",
    "watch:css":"cross-env TAILWIND_MODE=watch NODE_ENV=development postcss src/styles/tailwind.css -o src/styles/index.css --watch",
    "react-scripts:start":"sleep 5 && react-scripts start",
    "react-scripts:build":"react-scripts build",
    "start":"run-p watch:css react-scripts:start",
    "build":"run-s build:css react-scripts:build",
  }
}
```

When you run `npm run build`, NPM will kick off `run-s build:css react-scripts:build` process.
`run-s` is [npm-run-all](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md) script to run NPM commands in serial ([run-p](https://github.com/mysticatea/npm-run-all/blob/master/docs/run-p.md) is for running commands in parallel).

And `build:css` will run, which will let PostCSS process Tailwind CSS file to `src/styles/index.css`.
Lastly, `react-scripts:build` will handle the build with the processed Tailwind CSS file.

I could have created `pre*` scripts to build CSS but at the time I forgot about it and went with `run-s` as I was already using NPM-Run-All.
